# Generated by Django 3.1.4 on 2021-03-02 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAddOnModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_bio', models.CharField(max_length=100, null=True)),
                ('profile_image', models.ImageField(default='static/image/dflt_user.png', upload_to='ProfileAddOnModel')),
                ('cover_image', models.ImageField(default='static/image/dflt_cover.png', upload_to='ProfileAddOnModel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='malik', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
